export const stageOptions = [
  { value: 'stage_0_2', label: '0-2', score: 18 },
  { value: 'stage_3_4', label: '3-4', score: 46 },
  { value: 'stage_5', label: '5', score: 70 },
  { value: 'stage_6', label: '6', score: 88 },
];

export const modelOptions = [
  {
    id: 'score0',
    label: 'score0',
    title: 'Biological stage only',
    variableCount: 1,
    auc: 0.69,
    cIndex: 0.694,
  },
  {
    id: 'score1',
    label: 'score1',
    title: 'Variables selected by all three methods',
    variableCount: 5,
    auc: 0.79,
    cIndex: 0.79,
  },
  {
    id: 'score2',
    label: 'score2',
    title: 'Variables selected by at least two methods',
    variableCount: 10,
    auc: 0.83,
    cIndex: 0.819,
  },
  {
    id: 'score3',
    label: 'score3',
    title: 'Variables selected by at least one method',
    variableCount: 19,
    auc: 0.85,
    cIndex: 0.836,
  },
];

export const externalValidation = {
  sampleSize: 197,
  availableVariables: 8,
  score3: {
    oddsRatio: '2.14 (1.58, 2.90)',
    auc: 0.8,
    cIndex: 0.741,
  },
  note:
    'External validation supports the model direction and risk gradient, but should be interpreted as preliminary because of missing variables and imbalanced clinical stages.',
};

export const longitudinalFinding = {
  cohort: 'Stage 3-4 AD subgroup',
  outcome: 'Clinical stage progression',
  auc: 0.709,
  oddsRatio: '1.06 (1.01-1.11)',
  pValue: 0.023,
};

export const systemGroups = [
  {
    id: 'stage',
    label: 'Staging / Demographics',
    color: '#2563eb',
  },
  {
    id: 'csvd',
    label: 'Cerebral small vessel disease',
    color: '#0f766e',
  },
  {
    id: 'coagulation',
    label: 'Coagulation',
    color: '#b45309',
  },
  {
    id: 'metabolic',
    label: 'Metabolic / Renal / Cardiovascular',
    color: '#7c3aed',
  },
  {
    id: 'immune',
    label: 'Inflammation / Immune / Tumor markers',
    color: '#be123c',
  },
];

export const initialForm = {
  modelId: 'score3',
  biologicalStage: 'stage_3_4',
  age: '72',
  educationYears: '9',
  BMI: '23',
  PWMH: '2',
  DWMH: '2',
  totalCMB: '1',
  D_dimer: '0.6',
  ATIII: '92',
  Fbg: '3.2',
  FDP: '2.6',
  TT: '17',
  APTT: '34',
  LDL_C: '3.1',
  LDH: '185',
  Crea: '72',
  NLR: '2.6',
  IgL: '1.2',
  CA72_4: '4.5',
};

export const variableGroups = [
  {
    id: 'stage',
    title: 'Staging and demographics',
    fields: [
      {
        id: 'biologicalStage',
        label: 'Baseline biological stage',
        type: 'select',
        options: stageOptions,
        system: 'stage',
        models: ['score0', 'score1', 'score2', 'score3'],
        weight: 3.2,
      },
      {
        id: 'age',
        label: 'Age',
        unit: 'years',
        min: 45,
        max: 95,
        step: 1,
        placeholder: '45-95',
        system: 'stage',
        models: ['score2', 'score3'],
        weight: 0.55,
      },
      {
        id: 'educationYears',
        label: 'Education',
        unit: 'years',
        min: 0,
        max: 24,
        step: 1,
        placeholder: '0-24',
        system: 'stage',
        models: ['score1', 'score2', 'score3'],
        weight: 0.9,
        direction: 'inverse',
      },
      {
        id: 'BMI',
        label: 'BMI',
        unit: 'kg/m2',
        min: 14,
        max: 36,
        step: 0.1,
        placeholder: '14-36',
        system: 'stage',
        models: ['score3'],
        weight: 0.35,
        direction: 'inverse',
      },
    ],
  },
  {
    id: 'csvd',
    title: 'Cerebral small vessel disease',
    fields: [
      {
        id: 'PWMH',
        label: 'PWMH',
        note: 'Periventricular white matter hyperintensity',
        min: 0,
        max: 3,
        step: 1,
        placeholder: '0-3',
        system: 'csvd',
        models: ['score1', 'score2', 'score3'],
        weight: 0.95,
      },
      {
        id: 'DWMH',
        label: 'DWMH',
        note: 'Deep white matter hyperintensity',
        min: 0,
        max: 3,
        step: 1,
        placeholder: '0-3',
        system: 'csvd',
        models: ['score2', 'score3'],
        weight: 0.7,
      },
      {
        id: 'totalCMB',
        label: 'Total CMB',
        note: 'Total cerebral microbleeds',
        min: 0,
        max: 30,
        step: 1,
        placeholder: '0-30',
        system: 'csvd',
        models: ['score2', 'score3'],
        weight: 0.6,
      },
    ],
  },
  {
    id: 'coagulation',
    title: 'Coagulation',
    fields: [
      {
        id: 'D_dimer',
        label: 'D-dimer',
        unit: 'mg/L',
        min: 0,
        max: 10,
        step: 0.01,
        placeholder: '0-10',
        system: 'coagulation',
        models: ['score2', 'score3'],
        weight: 0.65,
      },
      {
        id: 'ATIII',
        label: 'ATIII',
        unit: '%',
        min: 50,
        max: 140,
        step: 1,
        placeholder: '50-140',
        system: 'coagulation',
        models: ['score3'],
        weight: 0.4,
        direction: 'inverse',
      },
      {
        id: 'Fbg',
        label: 'Fbg',
        unit: 'g/L',
        min: 1,
        max: 8,
        step: 0.01,
        placeholder: '1-8',
        system: 'coagulation',
        models: ['score2', 'score3'],
        weight: 0.55,
      },
      {
        id: 'FDP',
        label: 'FDP',
        unit: 'mg/L',
        min: 0,
        max: 20,
        step: 0.01,
        placeholder: '0-20',
        system: 'coagulation',
        models: ['score1', 'score2', 'score3'],
        weight: 0.75,
      },
      {
        id: 'TT',
        label: 'TT',
        unit: 's',
        min: 10,
        max: 30,
        step: 0.1,
        placeholder: '10-30',
        system: 'coagulation',
        models: ['score1', 'score2', 'score3'],
        weight: 0.7,
      },
      {
        id: 'APTT',
        label: 'APTT',
        unit: 's',
        min: 20,
        max: 60,
        step: 0.1,
        placeholder: '20-60',
        system: 'coagulation',
        models: ['score3'],
        weight: 0.35,
      },
    ],
  },
  {
    id: 'metabolic',
    title: 'Metabolic, renal, and cardiovascular',
    fields: [
      {
        id: 'LDL_C',
        label: 'LDL-C',
        unit: 'mmol/L',
        min: 0.5,
        max: 8,
        step: 0.01,
        placeholder: '0.5-8',
        system: 'metabolic',
        models: ['score3'],
        weight: 0.35,
      },
      {
        id: 'LDH',
        label: 'LDH',
        unit: 'U/L',
        min: 80,
        max: 400,
        step: 1,
        placeholder: '80-400',
        system: 'metabolic',
        models: ['score3'],
        weight: 0.35,
      },
      {
        id: 'Crea',
        label: 'Creatinine',
        unit: 'umol/L',
        min: 30,
        max: 180,
        step: 1,
        placeholder: '30-180',
        system: 'metabolic',
        models: ['score3'],
        weight: 0.4,
      },
    ],
  },
  {
    id: 'immune',
    title: 'Inflammation, immune, and tumor markers',
    fields: [
      {
        id: 'NLR',
        label: 'NLR',
        min: 0.5,
        max: 12,
        step: 0.01,
        placeholder: '0.5-12',
        system: 'immune',
        models: ['score3'],
        weight: 0.45,
      },
      {
        id: 'IgL',
        label: 'Ig lambda',
        unit: 'g/L',
        min: 0,
        max: 5,
        step: 0.01,
        placeholder: '0-5',
        system: 'immune',
        models: ['score3'],
        weight: 0.3,
      },
      {
        id: 'CA72_4',
        label: 'CA72-4',
        unit: 'U/mL',
        min: 0,
        max: 30,
        step: 0.1,
        placeholder: '0-30',
        system: 'immune',
        models: ['score3'],
        weight: 0.3,
      },
    ],
  },
];

export const fields = variableGroups.flatMap((group) => group.fields);
